-- 6장 내장 함수

-- 6-1 UPPER() 대문자 , LOWER() 소문자, INITCAP() 첫글자 대문자

SELECT ENAME, 
    UPPER(ENAME), 
    LOWER(ENAME),
    INITCAP(ENAME)
    FROM EMP;

-- 6-4 LENGTH() , LENGTHB() 글자의 길이
SELECT LENGTH('한글'), LENGTHB('한글')
    FROM DUAL;
    
SELECT *
    FROM DUAL; -- 실험용 테이블(오라클 더미 테이블)
    
-- 6-7 SUBSTR(문자열 데이터, 시작위치, 추출할 글자 수) 문자열 일부 추출

SELECT JOB,
SUBSTR(JOB, 1, 2)
FROM EMP;

-- 6-12 REPLACE()
SELECT '010-1234-5678' AS REPLACE_BEFORE,
 REPLACE('010-1234-5678', '-', ' ') AS REPLACE_AFTER,
 REPLACE('010-1234-5678', '-') AS REPLACE_AFTER2
 FROM DUAL;
 
-- 6-13 LPAD(), RPAD()
SELECT 'ORACLE'
 FROM DUAL;
 
-- 6-15 CONCAT()
SELECT CONCAT(EMPNO,ENAME),
CONCAT(EMPNO, CONCAT(':',ENAME))
FROM EMP;

SELECT EMPNO || ENAME,
    EMPNO || ':' || ENAME
FROM EMP;

-- 6-19 ROUND() : 반올림
SELECT ROUND(1234.5678) AS ROUND,
       ROUND(1234.5678, 3) AS ROUND,
       ROUND(1234.5678,-3) AS ROUND
FROM DUAL;

-- 6-23 SYSDATE : 현재의 날짜와 시간을 해줌
SELECT SYSDATE AS NOW,
       SYSDATE - 1 AS YESTERDAY,
       SYSDATE + 1 AS TOMORROW
FROM DUAL;

-- 6-25 입사 10주년 날짜를 구하기
SELECT EMPNO, ENAME, HIREDATE,
    ADD_MONTHS(HIREDATE, 120) AS WORK10YEAR
    FROM EMP;
    
-- 6-28 NEXY_DAY(), LAST_DAY()
SELECT SYSDATE,
       NEXT_DAY(SYSDATE, '수요일'),
       LAST_DAY(SYSDATE)
       FROM DUAL;

-- 형 변환 : TO_DAYE() : 문자를 날짜로 변환
SELECT TO_DATE('2018-07-14', 'YYYY-MM-DD') AS TODATE1,
       TO_DATE('20180714', 'YYYY-MM-DD') AS TODATE2,
       TO_DATE('2018 07 14', 'YYYY-MM-DD') AS YODATE3
FROM DUAL;

-- NVL(X, VALUE) : NULL 처리 함수 : X가 NULL 일때 VALUE로 변경
SELECT EMPNO, ENAME, SAL, COMM, SAL + COMM,
       NVL(COMM, 0),
       SAL * 12 + NVL(COMM, 0) AS ANNALSAL
       FROM EMP;
