-- CREATE
-- Q1
CREATE TABLE BOARD(
        B_ID        NUMBER(5) PRIMARY KEY,
        B_NAME      VARCHAR2(20) NOT NULL,
        B_PWD       VARCHAR2(20) NOT NULL,
        B_EMAIL     VARCHAR2(20) NOT NULL,
        B_TITLE     VARCHAR2(80) NOT NULL,
        B_CONTENT   VARCHAR2(2000) NOT NULL,
        B_DATE      DATE DEFAULT SYSDATE,
        B_HIT       NUMBER(5) DEFAULT 0,
        B_IP        VARCHAR2(15)
 );
 
 DESC BOARD;
 
 -- Q2
 ALTER TABLE BOARD  
    ADD B_REF   NUMBER(5) DEFAULT 0
    ADD B_STEP  NUMBER(5) DEFAULT 0
    ADD B_ORDER NUMBER(5) DEFAULT 0;
    
DESC BOARD;

-- Q3
ALTER TABLE BOARD
    MODIFY B_TITLE VARCHAR2(100);
    
-- Q4
ALTER TABLE BOARD
    MODIFY (B_PWD NULL);

DESC BOARD;

-- Q5
ALTER TABLE BOARD
    DROP COLUMN B_IP;
    
-- Q6
DESC BOARD;

-- Q7
CREATE TABLE EC_MEMBER1
    AS SELECT * FROM EC_MEMBER;
    
ALTER TABLE EC_MEMBER1
    ADD(CONSTRAINT Member_CK CHECK(UserID BETWEEN 'a' and 'z'));

INSERT INTO EC_Member1 (UserID, Passwd, Name, Regist_No, Telephone)
    VALUES ('srlee', '1234', '이소라', '821001-2******', '010-123-1234');

INSERT INTO EC_Member1 (UserID, Passwd, Name, Regist_No, Telephone)
    VALUES ('20park', '1234', '박연수', '810604-1******', '010-234-2345');
    
 
-- Q8
ALTER TABLE BOARD
    RENAME COLUMN B_STEP TO B_LEVEL;

DESC BOARD;

-- Q9 (기본키 = PRIMARY KEY)
DESC EC_ORDER;

ALTER TABLE EC_ORDER
    DROP CONSTRAINT EC_ORDER_PK1;
    
-- Q10
ALTER TABLE BOARD
    MODIFY(B_EMAIL UNIQUE);
    
DESC BOARD;

-- Q11
RENAME BOARD TO Free_Board;

-- Q12
DROP TABLE EC_Basket;

DESC EC_Basket;
