-- Q1
SELECT PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE
    FROM EC_Product
    WHERE UNIT_PRICE > 2000000;
    
-- Q2
SELECT USERID, NAME, REGIST_NO, ADDRESS
    FROM EC_Member
    WHERE ADDRESS LIKE '서울특별시%';
 

-- Q3
SELECT ORDER_NO, ORDER_ID, PRODUCT_CODE, ORDER_QTY, ORDER_DATE
    FROM EC_Basket
    WHERE ORDER_DATE = '10/11/06';

-- Q4
SELECT ORDER_NO, PRODUCT_CODE, ORDER_QTY, CSEL, CMONEY, CDATE, GUBUN
    FROM EC_Order
    WHERE GUBUN = '결재'
    ORDER BY ORDER_NO ASC;
    
-- Q5
SELECT USERID, NAME, REGIST_NO
    FROM EC_Member
    WHERE NAME LIKE '%우%';

-- Q6
SELECT ORDER_NO, ORDER_ID, PRODUCT_CODE, CSEL, GUBUN
    FROM EC_Order
    WHERE NOT CSEL IN('신용카드')
    ORDER BY ORDER_ID ASC;
    
-- Q7
SELECT PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, LEFT_QTY, COMPANY
    FROM EC_Product
    WHERE UNIT_PRICE BETWEEN 300000 AND 500000
    ORDER BY UNIT_PRICE DESC;
    
-- Q8
SELECT *
    FROM EC_Order
    WHERE CSEL = '신용카드';

-- Q9
SELECT ORDER_NO, ORDER_ID, PRODUCT_CODE, ORDER_QTY, CMONEY, GUBUN
    FROM EC_Order
    WHERE GUBUN = '미결';
    
-- Q10
SELECT *
    FROM EC_Order
    WHERE ORDER_ID = 'usko';